language: python

python:
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true


script:
- python setup.py build
- python setup.py install
- pip list
- python gampa.py

deploy:
  provider: script
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

 # or any other command you'd like to run your tests with
